export const courses = [
  { value: '', label: '' },
  { value: 'ciencia-da-computacao', label: 'Ciência da Computação' },
  { value: 'engenharia-de-software', label: 'Engenharia de Software' },
  { value: 'sistemas-de-informacao', label: 'Sistemas de Informação' },
  {
    value: 'analise-e-desenvolvimento-de-sistemas',
    label: 'Análise e Desenvolvimento de Sistemas',
  },
  { value: 'engenharia-eletrica', label: 'Engenharia Elétrica' },
  { value: 'engenharia-civil', label: 'Engenharia Civil' },
  { value: 'engenharia-mecanica', label: 'Engenharia Mecânica' },
  { value: 'engenharia-de-producao', label: 'Engenharia de Produção' },
  {
    value: 'engenharia-de-controle-e-automacao',
    label: 'Engenharia de Controle e Automação',
  },
  { value: 'ciencia-de-dados', label: 'Ciência de Dados' },
  { value: 'redes-de-computadores', label: 'Redes de Computadores' },
  { value: 'seguranca-da-informacao', label: 'Segurança da Informação' },
  { value: 'inteligencia-artificial', label: 'Inteligência Artificial' },
  { value: 'ciencia-de-materiais', label: 'Ciência de Materiais' },
  { value: 'fisica', label: 'Física' },
  { value: 'matematica', label: 'Matemática' },
  { value: 'estatistica', label: 'Estatística' },
  { value: 'engenharia-de-alimentos', label: 'Engenharia de Alimentos' },
  { value: 'engenharia-quimica', label: 'Engenharia Química' },
  { value: 'engenharia-de-petroleo', label: 'Engenharia de Petróleo' },
  { value: 'biotecnologia', label: 'Biotecnologia' },
  { value: 'biomedicina', label: 'Biomedicina' },
  { value: 'medicina', label: 'Medicina' },
  { value: 'enfermagem', label: 'Enfermagem' },
  { value: 'farmacia', label: 'Farmácia' },
  { value: 'direito', label: 'Direito' },
  { value: 'administracao', label: 'Administração' },
  { value: 'contabilidade', label: 'Contabilidade' },
  { value: 'economia', label: 'Economia' },
  { value: 'psicologia', label: 'Psicologia' },
  { value: 'educacao-fisica', label: 'Educação Física' },
  { value: 'arquitetura-e-urbanismo', label: 'Arquitetura e Urbanismo' },
  { value: 'design', label: 'Design' },
  { value: 'jornalismo', label: 'Jornalismo' },
  { value: 'publicidade-e-propaganda', label: 'Publicidade e Propaganda' },
  { value: 'relacoes-internacionais', label: 'Relações Internacionais' },
  { value: 'historia', label: 'História' },
  { value: 'geografia', label: 'Geografia' },
  { value: 'filosofia', label: 'Filosofia' },
  { value: 'letras', label: 'Letras' },
  { value: 'pedagogia', label: 'Pedagogia' },
  { value: 'servico-social', label: 'Serviço Social' },
];
