name: Node.js CI

on:
  pull_request:
    branches: ['main']

jobs:
  lint-styles:
    name: Lint Styles
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm i

      - name: Run lint script
        run: pnpm lint

  run-test:
    name: Run Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm i

      - name: Create .env file from .env.example
        run: cp .env.example .env

      - name: Start containers
        run: pnpm services:up && pnpm services:wait

      - name: Run prisma migrations
        run: pnpm migrate

      - name: Run web server & Run test script
        run: pnpm dev:all & pnpm test

      - name: Stop container
        run: pnpm services:down

      - name: Remove .env created from .env.example
        run: rm .env
